---
##########################################################################
# 1. PVE Nag-Buster Installation Tasks
##########################################################################
- name: Check if pve-nag-buster script is installed
  ansible.builtin.stat:
    path: /usr/share/pve-nag-buster.sh
  register: pve_nag_buster_file

- name: Download the PVE nag-buster install script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/foundObjects/pve-nag-buster/master/install.sh"
    dest: "/tmp/install.sh"
    mode: '0755'
  when: not pve_nag_buster_file.stat.exists

- name: Run the nag-buster install script
  ansible.builtin.command: "/tmp/install.sh"
  args:
    chdir: "/tmp"
    creates: /usr/share/pve-nag-buster.sh
  when: not pve_nag_buster_file.stat.exists

##########################################################################
# 2. Proxmox Cluster Setup Tasks
##########################################################################
- name: Check if node is part of an existing Proxmox cluster
  ansible.builtin.command: pvecm status
  register: pvecm_status
  ignore_errors: true
  changed_when: false

- name: Set fact if node is not in a cluster
  ansible.builtin.set_fact:
    not_in_cluster: "{{ 'does not exist' in pvecm_status.stderr }}"

- name: Create cluster on the master node if not in a cluster
  ansible.builtin.command: "pvecm create {{ cluster_name }}"
  when:
    - is_master
    - not_in_cluster
  register: create_cluster
  changed_when: create_cluster.rc == 0

- name: Use expect to provide password and confirm SSH connection for pvecm add
  ansible.builtin.expect:
    command: "pvecm add {{ master_ip }}"
    responses:
      "^Please enter superuser \\(root\\) password for '.*':\\s*": "{{ proxmox_password }}"
      "Are you sure you want to continue connecting \\(yes/no\\)\\?": "yes"
    timeout: 200
  when:
    - "'proxmox_nodes' in group_names or 'proxmox_master' in group_names"
    - not is_master
    - not_in_cluster

- name: Reboot node after Proxmox configuration if not in cluster
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: not_in_cluster

- name: Ensure ifupdown2 is installed (for networking reload)
  ansible.builtin.apt:
    name: ifupdown2
    state: present
  when: ansible_os_family == "Debian"

- name: Deploy /etc/network/interfaces from template
  ansible.builtin.template:
    src: ../files/interfaces.j2
    dest: /etc/network/interfaces
    mode: '0755'
    backup: true
  notify:
    - Restart networking

##########################################################################
# Proxmox HA Group Creation by Checking /etc/pve/ha/groups.cfg
##########################################################################
- name: Check if /etc/pve/ha/groups.cfg exists
  ansible.builtin.stat:
    path: /etc/pve/ha/groups.cfg
  register: ha_groups_file
  changed_when: false
  failed_when: false
  when: is_master

- name: Check if 'proxmox_ha_group' is already defined in groups.cfg
  ansible.builtin.shell: "grep -q '^group: proxmox_ha_group$' /etc/pve/ha/groups.cfg"
  register: group_check
  changed_when: false
  failed_when: false
  when:
    - is_master
    - ha_groups_file.stat.exists

- name: Combine proxmox_master and proxmox_nodes into a single list
  ansible.builtin.set_fact:
    all_proxmox_nodes: "{{ groups['proxmox_master'] | default([]) + groups['proxmox_nodes'] | default([]) }}"
  when: is_master

- name: Create a Proxmox HA group if missing
  ansible.builtin.command: "ha-manager groupadd proxmox_ha_group --nodes {{ all_proxmox_nodes | join(',') }}"
  when:
    - is_master
    - ha_groups_file.stat.exists
    - group_check.rc != 0
  register: create_ha_group
  changed_when: create_ha_group.rc == 0


##########################################################################
# Additional Proxmox Tasks: Enable NFS Storages and Daily Backups
##########################################################################

- name: Ensure backup directory for Proxmox backups exists
  ansible.builtin.file:
    path: /mnt/proxmox_backups
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: is_master

- name: Render storage.cfg template locally
  ansible.builtin.set_fact:
    rendered_storage_cfg: "{{ lookup('template', '../files/storage.cfg.j2') }}"
  when: is_master

- name: Compute checksum of rendered storage.cfg template
  ansible.builtin.set_fact:
    rendered_storage_checksum: "{{ rendered_storage_cfg | hash('sha1') }}"
  when: is_master

- name: Get remote storage.cfg details
  ansible.builtin.stat:
    path: /etc/pve/storage.cfg
    checksum_algorithm: sha1
  register: remote_storage_cfg
  when: is_master

- name: Update /etc/pve/storage.cfg if the rendered config differs
  ansible.builtin.copy:
    content: "{{ rendered_storage_cfg }}"
    dest: /etc/pve/storage.cfg
    mode: "{{ remote_storage_cfg.stat.mode | default('0640') }}"
  notify:
    - Restart pveproxy
  when: is_master and (
          (remote_storage_cfg.stat.exists is not defined) or
          (not remote_storage_cfg.stat.exists) or
          (remote_storage_cfg.stat.checksum != rendered_storage_checksum)
        )

##########################################################################
# HA Pool Configuration for VMs
##########################################################################
- name: Check if Proxmox pool "vm_backup_pool" exists
  ansible.builtin.shell: "grep -q '^pool: vm_backup_pool$' /etc/pve/pools.cfg"
  register: pool_check
  changed_when: false
  failed_when: false
  when: is_master

- name: Create Proxmox pool "vm_backup_pool" for VM backups if not exists
  ansible.builtin.command: >
    pvesh create /pools --poolid vm_backup_pool --comment "Pool for VM backups"
  when: is_master and pool_check.rc != 0
  register: create_pool
  failed_when: create_pool.rc != 0 and ("already exists" not in (create_pool.stderr | string))
  changed_when: create_pool.rc == 0

##########################################################################
# VM Backup Job
##########################################################################
- name: Get current Proxmox backup jobs
  ansible.builtin.command: "pvesh get /cluster/backup/jobs"
  register: current_backup_jobs
  changed_when: false
  failed_when: false
  when: is_master

- name: Create Proxmox backup job for pool "vm_backup_pool" if not exists
  ansible.builtin.command: >
    pvesh create /cluster/backup --schedule '*-*-* 11:00:00' --pool vm_backup_pool --storage nfs_data --maxfiles 2 --enabled 1
  when: is_master and ("vm_backup_pool" not in current_backup_jobs.stdout)
  register: create_backup_job
  changed_when: create_backup_job.rc == 0
