- name: Restart networking
  ansible.builtin.systemd:
    name: networking
    state: restarted

- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: Reboot the host
  ansible.legacy.reboot:
    msg: "Reboot initiated by Ansible for vGPU setup."
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: uname -r
