FROM --platform=linux/amd64 deinfreu/hytale-server:experimental-0.1.4

# Place the required files in this directory before build.
# deinfreu/hytale-server expects /home/container.
COPY Assets.zip /home/container/Assets.zip
COPY HytaleServer.jar /home/container/HytaleServer.jar
