- name: Configure and Deploy HAProxy and WireGuard on Webserver Nodes
  hosts: webservers
  become: true
  vars:
    minecraft_server_endpoint: "10.70.30.200"
    plex_server_endpoint: "10.70.30.201"

    wg_interface: wg0
    wg_listen_port: 2333
    vm_tunnel_ip_address: "{{ lookup('env', 'VM_TUNNEL_IP_ADDRESS') }}"
    wg_server_endpoint: "{{ vm_tunnel_ip_address | trim }}:{{ wg_listen_port }}"
    wg_client_address: "10.8.0.2"
    wg_vpn_subnet: "10.8.0.0/24"
    wg_server_public_key: "{{ lookup('env', 'WG_SERVER_PUBLIC_KEY') }}"
    wg_client_private_key: "{{ lookup('env', 'WG_CLIENT_PRIVATE_KEY') }}"

    wg_persistent_keepalive: 25

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Autoremove old kernels and clean up
      ansible.builtin.apt:
        autoremove: true
        autoclean: true

    - name: Install WireGuard, wireguard-tools, and resolvconf
      ansible.builtin.apt:
        name:
          - wireguard
          - wireguard-tools
          - resolvconf
        state: present

    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present

    - name: Ensure Wireguard configuration directory exists
      ansible.builtin.file:
        path: /etc/wireguard
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy WireGuard configuration file (wg0.conf)
      ansible.builtin.template:
        src: templates/wg0.conf.j2
        dest: /etc/wireguard/{{ wg_interface }}.conf
        owner: root
        group: root
        mode: "0600"
      notify: Restart WireGuard

    - name: Bring up WireGuard interface
      ansible.builtin.systemd:
        name: wg-quick@{{ wg_interface }}
        enabled: true
        state: started

    - name: Create systemd override directory for HAProxy service
      ansible.builtin.file:
        path: /etc/systemd/system/haproxy.service.d
        state: directory
        mode: "0755"

    - name: Deploy systemd override file for HAProxy to relax namespace restrictions
      ansible.builtin.copy:
        dest: /etc/systemd/system/haproxy.service.d/override.conf
        content: |
          [Service]
          PrivateTmp=no
          ProtectSystem=off
          ProtectHome=off
          PrivateDevices=no
          NoNewPrivileges=no
        owner: root
        group: root
        mode: "0644"
      notify: Reload systemd

    - name: Ensure HAProxy configuration directory exists
      ansible.builtin.file:
        path: /etc/haproxy
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy custom HAProxy configuration for game traffic
      ansible.builtin.template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "0644"
      notify: Restart HAProxy

    - name: Ensure HAProxy service is started and enabled
      ansible.builtin.service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart HAProxy
      ansible.builtin.service:
        name: haproxy
        state: restarted

    - name: Restart WireGuard
      ansible.builtin.systemd:
        name: wg-quick@{{ wg_interface }}
        state: restarted
