- name: Install WireGuard, wireguard-tools, and resolvconf
  ansible.builtin.apt:
    name:
      - wireguard
      - wireguard-tools
      - iptables
      - resolvconf
    state: present
  become: true

- name: Create WireGuard configuration directory
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: "0700"
  become: true

- name: Deploy WireGuard add tunnel rules
  ansible.builtin.template:
    src: ../files/add_tunnel_rules.sh
    dest: "{{ add_tunnel_script_file }}"
    owner: root
    group: root
    mode: "0700"
  become: true

- name: Deploy WireGuard remove tunnel rules
  ansible.builtin.template:
    src: ../files/add_tunnel_rules.sh
    dest: "{{ remove_tunnel_script_file }}"
    owner: root
    group: root
    mode: "0700"
  become: true

- name: Deploy WireGuard configuration file (wg0.conf)
  ansible.builtin.template:
    src: ../files/wg0.conf.j2
    dest: "{{ wg_config_file }}"
    owner: root
    group: root
    mode: "0600"
  become: true
  notify: Restart WireGuard

- name: Start and enable the WireGuard interface
  ansible.builtin.systemd:
    name: wg-quick@{{ wg_interface }}
    enabled: true
    state: started
  become: true

- name: Enable IPv4 forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Set rp_filter to 2 for all interfaces
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "2"
    state: present
    reload: yes
