---
- name: Configure PROXMOX nodes
  hosts: proxmox_master,proxmox_nodes
  roles:
    - common
    - proxmox
  become: true
  vars:
    cluster_name: "pve-cluster"
    master_ip: "{{ hostvars[groups['proxmox_master'][0]].proxmox_ip_address }}"
    is_master: "{{ inventory_hostname in groups['proxmox_master'] }}"
    proxmox_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
