name: Homelab Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
      - 'scripts/ci/**'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

concurrency:
  group: homelab-reverse-proxy-group
  cancel-in-progress: false  # Prevents cancellation of in-progress workflows

jobs:
  homelab-infra:
    name: Deployment
    runs-on: ubuntu-latest
    env:
      HOMELAB_SSH_KEY_PATH: "/home/runner/.ssh/id_ed25519_homelab"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci
          args: --exit-node=100.83.21.9 --accept-risk=all

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.10.3'
          cli_config_credentials_token: ${{ secrets.TERRAFORM_HOMELAB_TOKEN }}
          terraform_wrapper: false

      - name: Install Ansible Tools
        run: ./scripts/ci/install_ansible_tools.sh

      - name: Setup SSH Key
        run: ./scripts/ci/ssh_key_setup.sh
        env:
          HOMELAB_SSH_KEY_B64: ${{ secrets.HOMELAB_SSH_KEY_B64 }}

      - name: Run Deployment Script
        run: ./deploy/deploy.sh
        env:
          ROUTER_CORE_HOST_URL: "https://router.lan"
          ROUTER_CORE_ADMIN_USERNAME: ${{ secrets.ROUTER_CORE_ADMIN_USERNAME }}
          ROUTER_CORE_ADMIN_PASSWORD: ${{ secrets.ROUTER_CORE_ADMIN_PASSWORD }}
          TERRAFORM_VARS_NETWORK_B64: ${{ secrets.TERRAFORM_VARS_NETWORK_B64 }}
          PROXMOX_ENDPOINT: "https://10.70.30.12:8006"
          PROXMOX_ADMIN_USERNAME: ${{ secrets.PROXMOX_ADMIN_USERNAME }}
          PROXMOX_ADMIN_PASSWORD: ${{ secrets.PROXMOX_ADMIN_PASSWORD }}
          INFISICAL_HOST: "https://app.infisical.com"
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          INFISICAL_WORKSPACE_ID: ${{ secrets.INFISICAL_WORKSPACE_ID }}
          INFISICAL_ENV_SLUG: "prod"
          BACKBLAZE_APPLICATION_KEY: ${{ secrets.BACKBLAZE_APPLICATION_KEY }}
          BACKBLAZE_KEY_ID: ${{ secrets.BACKBLAZE_KEY_ID }}

