name: Reverse Proxy Workload

on:
  workflow_run:
    workflows: ["Homelab Infrastructure"]
    types:
      - completed
  push:
    paths:
      - 'workloads/reverse-proxy/**'

concurrency:
  group: homelab-reverse-proxy-group
  cancel-in-progress: false

jobs:
  rp-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    uses: ./.github/workflows/deploy-workloads.yml
    with:
      workload_dir: "reverse-proxy"
      router_core_host_url: "https://router.lan"
      proxmox_endpoint: "https://10.70.30.12:8006"
    secrets:
      TAILSCALE_CLIENT_ID: ${{ secrets.TAILSCALE_CLIENT_ID }}
      TAILSCALE_CLIENT_SECRET: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
      TERRAFORM_HOMELAB_TOKEN: ${{ secrets.TERRAFORM_HOMELAB_TOKEN }}
      HOMELAB_SSH_KEY_B64: ${{ secrets.HOMELAB_SSH_KEY_B64 }}
      HOMELAB_SSH_PUBLIC_KEY: ${{ secrets.HOMELAB_SSH_PUBLIC_KEY }}
      ROUTER_CORE_PASSWORD: ${{ secrets.ROUTER_CORE_PASSWORD }}
      ROUTER_CORE_USERNAME: ${{ secrets.ROUTER_CORE_USERNAME }}
      PROXMOX_USERNAME: ${{ secrets.PROXMOX_USERNAME }}
      PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}

